import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="min-h-dvh container mx-auto">
          <header className="min-h-32 flex items-center justify-center">
            <h1 className="font-bold text-6xl">Contentlayer z Nextem</h1>
          </header>
          {children}
        </main>
      </body>
    </html>
  );
}
